// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4iYaagmL-FZjfjh88TbH6NkyLBQ22ISQ',
    appId: '1:560169251076:web:1fa86415a77e9985e8e051',
    messagingSenderId: '560169251076',
    projectId: 'chatapp-530cb',
    authDomain: 'chatapp-530cb.firebaseapp.com',
    storageBucket: 'chatapp-530cb.firebasestorage.app',
    measurementId: 'G-0GXBSLHT1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrlMg-_PQyUxvasZrZKCT6xlPN12Eejwk',
    appId: '1:560169251076:android:4911e3bddd0dae6ee8e051',
    messagingSenderId: '560169251076',
    projectId: 'chatapp-530cb',
    storageBucket: 'chatapp-530cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApfpAMfCGAlY_NU6lEqBxbcx74DyYO_us',
    appId: '1:560169251076:ios:03e165d76636b783e8e051',
    messagingSenderId: '560169251076',
    projectId: 'chatapp-530cb',
    storageBucket: 'chatapp-530cb.firebasestorage.app',
    iosBundleId: 'com.chatapp.org.chat-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApfpAMfCGAlY_NU6lEqBxbcx74DyYO_us',
    appId: '1:560169251076:ios:16172f99f6cb29f9e8e051',
    messagingSenderId: '560169251076',
    projectId: 'chatapp-530cb',
    storageBucket: 'chatapp-530cb.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4iYaagmL-FZjfjh88TbH6NkyLBQ22ISQ',
    appId: '1:560169251076:web:3b49b64767c82739e8e051',
    messagingSenderId: '560169251076',
    projectId: 'chatapp-530cb',
    authDomain: 'chatapp-530cb.firebaseapp.com',
    storageBucket: 'chatapp-530cb.firebasestorage.app',
    measurementId: 'G-W91NV1FTDT',
  );

}